import {
  HouseSimple,
  Compass as PCompass,
  Heart as PHeart,
  BookOpenText,
  RocketLaunch,
  Path,
  MagnifyingGlass,
  Wallet as PWallet,
  X as PX,
  CaretDown,
  ArrowUpRight as PArrowUpRight,
  ArrowDownLeft as PArrowDownLeft,
  CaretRight,
  Check as PCheck,
  Broadcast,
  Play as PPlay,
  Flame as PFlame,
  Plus as PPlus,
  Stack,
  TrendUp,
  List,
  ShieldCheck as PShieldCheck,
  ArrowLeft as PArrowLeft,
  ArrowRight as PArrowRight,
  ArrowDown as PArrowDown,
  Coins as PCoins,
  Bank,
  ArrowSquareOut,
  Question,
  FileText as PFileText,
  Image as PImage,
  SpinnerGap,
  Trash,
  UploadSimple,
  Receipt,
  Copy as PCopy,
  Sparkle,
  Waveform as PWaveform,
  Lightning as PLightning,
} from '@phosphor-icons/react';
import type { Icon, IconProps } from '@phosphor-icons/react';
function studioIcon(Component: Icon) {
  return function StudioIcon({
    strokeWidth: _strokeWidth,
    ...props
  }: IconProps & { strokeWidth?: number }) {
    return <Component weight="duotone" {...props} />;
  };
}
export const Home = studioIcon(HouseSimple),
  Compass = studioIcon(PCompass),
  Heart = studioIcon(PHeart),
  BookOpen = studioIcon(BookOpenText),
  Rocket = studioIcon(RocketLaunch),
  Route = studioIcon(Path),
  Search = studioIcon(MagnifyingGlass),
  Wallet = studioIcon(PWallet),
  X = studioIcon(PX),
  ChevronDown = studioIcon(CaretDown),
  ChevronRight = studioIcon(CaretRight),
  ArrowUpRight = studioIcon(PArrowUpRight),
  ArrowDownLeft = studioIcon(PArrowDownLeft),
  Check = studioIcon(PCheck),
  Radio = studioIcon(Broadcast),
  Play = studioIcon(PPlay),
  Flame = studioIcon(PFlame),
  Plus = studioIcon(PPlus),
  Layers = studioIcon(Stack),
  TrendingUp = studioIcon(TrendUp),
  Menu = studioIcon(List),
  ShieldCheck = studioIcon(PShieldCheck),
  ArrowLeft = studioIcon(PArrowLeft),
  ArrowRight = studioIcon(PArrowRight),
  ArrowDown = studioIcon(PArrowDown),
  Coins = studioIcon(PCoins),
  Landmark = studioIcon(Bank),
  ExternalLink = studioIcon(ArrowSquareOut),
  CircleHelp = studioIcon(Question),
  FileText = studioIcon(PFileText),
  ImagePlus = studioIcon(PImage),
  LoaderCircle = studioIcon(SpinnerGap),
  Trash2 = studioIcon(Trash),
  Upload = studioIcon(UploadSimple),
  ReceiptText = studioIcon(Receipt),
  Copy = studioIcon(PCopy),
  Sparkles = studioIcon(Sparkle),
  Waveform = studioIcon(PWaveform),
  Lightning = studioIcon(PLightning);
